spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/collabdb
    username: admin
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

app:
  jwt:
    secret: your-secret-key-here-change-this-in-production 
    # secret: ${JWT_SECRET}  Then store actual secret in environment variable
    expiration-ms: 86400000
